### ISSUE TITLE
customizations glitching

### ISSUE THREAD

**Issue by Bambam1212** [TekkenOverlay/TekkenOverlay#79] opened 2022-06-22 19:13 UTC
This glitch only happens when overlay is open and with the character customization of tekken banner and head lantern on master Raven. I didn't test on other characters.

![43856b4b-9621-4ee1-a7d4-9f4c171b6b2d](https://user-images.githubusercontent.com/106425167/175115420-e6cf2e0c-6166-40f2-ae7d-2a9926f66e17.jpg)
![7fca5d7e-739e-497a-a718-1ada0be9f3ab](https://user-images.githubusercontent.com/106425167/175115435-2f5f6e24-3ebc-4178-b027-3f0d8d8e2f1e.jpg)
![14d34d67-3d24-44b5-87e8-38b7c6f4bb98](https://user-images.githubusercontent.com/106425167/175115440-af8ca32b-2876-43a7-9dc1-9af254241fa2.jpg)
![984ed02a-05f7-4388-a4be-fa7b60b24823](https://user-images.githubusercontent.com/106425167/175115448-d9427bf6-3e80-4780-b23e-e7e09e039703.jpg)

**Comment by ParkourGrip** [comment] 2022-06-23 12:17
Duplicate of: https://github.com/TekkenOverlay/TekkenOverlay/issues/58

**Closed by ParkourGrip** 2022-06-23 12:17 UTC
