### ISSUE TITLE
Ready Fight text when playing online at start of round displays incorrectly

### ISSUE THREAD

**Issue by Joel-Hjerten** [TekkenOverlay/TekkenOverlay#91] opened 2022-08-29 11:53 UTC
Ready Fight text when playing online at start of round displays incorrectly. It's timing is off and show up and disappear before the actual round starts. This is after patch 5.0 with TekkenOverlay v5.00.1

I also experienced jerky animations in online matches. Hard to tell if it was just bad rollback that I've had without the Overlay active or if this is related to the Ready Fight text animation behaving weird. Perhaps has to do with animation interpolation but I didn't check at the time.

**Comment by ParkourGrip** [comment] 2022-08-29 15:18
Duplicate of: https://github.com/TekkenOverlay/TekkenOverlay/issues/62

**Closed by ParkourGrip** 2022-08-29 15:18 UTC

**Comment by ParkourGrip** [comment] 2022-08-29 15:39
The only thing that comes in mind when it comes to "jerky" animations is 1 frame of animation extrapolation. 
When the first frame of a move animation happens the 60fps game instantly switches to the 1st frame while the interpolated tekken starts smoothly transitioning to the first frame.
This makes the motion of characters lag behind compared to the 60fps version.
This is why we have animation extrapolation.
It advances the animation of the smooth animation by 1 60fps frame so that the smooth motion is in sync with the choppy 60fps version.
This also improves input lag by 1 frame cause you see the motion of your opponent's character 1 frame before even if that motion is tiny (smalller then motion on a single 60fps animation frame) an can react quicker.
Without animation extrapolation the motion of characters is lagging behind 1 frame.
But when the motion is lagging behind for 1 frame, it reduces the visual effect of rollback net-code teleportation by 1 frame too.
If you are used to playing with unlocked fps and tekken overlay version before we added animation extrapolation you are probably used to playing without it and now when you see more pronounced rollback teleports you think the animations are janky.
You can try to disable animation extrapolation (making your client have 1 more frame of input lag) and you will be less visually affected by the rollback netcode teleportations.
