### ISSUE TITLE
Frame Information Not Displayed

### ISSUE THREAD

**Issue by wi030730** [TekkenOverlay/TekkenOverlay#32] opened 2020-12-18 22:41 UTC
Throw Tech is displayed, but frame information and hit box are not available

**Comment by Truuce** [comment] 2020-12-19 03:13
same issue here. Ping and frame time also works.  In game memory > gameValues. "displayMode is red. along with everything in that field(pointer, address, bit, refreshRate)

**Comment by Truuce** [comment] 2020-12-19 03:19
figured it out. go into settings and make sure your Rendering scale is set to 100 or more.

**Comment by ParkourGrip** [comment] 2020-12-19 23:34
Duplicate of: #28

**Closed by ParkourGrip** 2020-12-19 23:34 UTC
