### ISSUE TITLE
Game crashing when overlay is open

### ISSUE THREAD

**Issue by nothyx** [TekkenOverlay/TekkenOverlay#109] opened 2022-12-21 14:33 UTC
Basically my game crashes every frickin time the overlay is open. When it injects the DLL, i can't even get into the main menu without getting tekken closed. How can i fix this?

**Comment by KulaGGin** [comment] 2022-12-21 15:33
What version of the overlay are you using?

**Comment by nothyx** [comment] 2022-12-21 17:21
I tried with 5.10.2, 5.10.1 and 5.00.0. With the 5.00 version it opened and worked for a while, then when i closed and re-opened it gave me this bug again

**Comment by ParkourGrip** [comment] 2022-12-21 19:10
Check if your antivirus deleted the dll file.

**Comment by KulaGGin** [comment] 2022-12-21 19:25
Unfortunately, I can't reproduce it.
You can try running the executable after you launch Tekken and reach the main menu, and see if it works.
The crashes can also happen because of clashes with some other software like programs that also do overlays: Discord, MSI Afterburner, any recording software, etc. So you can try closing that software and see if it still crashes.

**Comment by Cvar1984** [comment] 2022-12-23 03:12
> Unfortunately, I can't reproduce it. I updated all the game addresses for the current version and, apparently, it works for vast majority of people just fine.
> 
> I can suggest a few workarounds: You can try running the executable after you launch Tekken and reach the main menu.
> 
> The crashes can also happen because of clashes with some other software like programs that also do overlays: Discord, MSI Afterburner, any recording software, etc. So you can try closing that software and see if it still crashes.
> 
> As another workaround that might work for you, you can try moving memory-addresses.yaml file from the 5.10.2 version to the 5.01.1 version and see if that works for you.

can we have the source code for this project?

**Comment by KulaGGin** [comment] 2022-12-23 13:29
@nothyx Found that there was an error for one of the in-game addresses. I fixed it and created a new release:
https://github.com/TekkenOverlay/TekkenOverlay/releases/tag/5.10.3

Try it out and see if it works.

**Comment by nothyx** [comment] 2022-12-28 09:10
it seems to work, thanks!

**Closed** 2022-12-28 11:58 UTC
