### ISSUE TITLE
Hitboxes and frames not showing on rendering scale below 100

### ISSUE THREAD

**Issue by koreagunba** [TekkenOverlay/TekkenOverlay#23] opened 2020-11-15 23:04 UTC
since im using a potato pc i usually set the rendering scale on 75, but the frames and hitboxes only appear on 100. is there a workaround for this?

**Comment by ParkourGrip** [comment] 2021-03-22 21:31
Duplicate of: #28

**Closed by ParkourGrip** 2021-03-22 21:31 UTC
