### ISSUE TITLE
where do i get the source code?

### ISSUE THREAD

**Issue by maligeez** [TekkenOverlay/TekkenOverlay#100] opened 2022-10-12 00:16 UTC
it says source code but theres nothing in there? Isnt this open source?

**Comment by JackMcCallum** [comment] 2022-10-12 00:23
nope

**Comment by ParkourGrip** [comment] 2022-10-12 14:07
Duplicate of: https://github.com/TekkenOverlay/TekkenOverlay/issues/1

**Closed by ParkourGrip** 2022-10-12 14:07 UTC
