### ISSUE TITLE
Injecting DLL... FAIL!

### ISSUE THREAD

**Issue by Pteor** [TekkenOverlay/TekkenOverlay#6] opened 2020-10-13 01:07 UTC
Files have already been extracted. Tried extracting in multiple directories, running as administrator, and disabling antivirus.

**Comment by victoryzeta** [comment] 2020-10-13 07:54
Same. Extracted files, tried running it as admin and Injecting DLL... FAIL!

**Comment by TekkenOverlay** [comment] 2020-10-13 08:51
thanks for posting, will look into it

**Comment by TragicFour** [comment] 2020-10-13 11:39
Same issue. Files extracted completely. Run as admin. Win 10 2004 - 19041.508. Using Gfx AMD HD7970 

Injecting DLL... FAIL!

**Comment by TragicFour** [comment] 2020-10-13 13:26
Maybe this could help??

[DxDiag.txt](https://github.com/TekkenOverlay/TekkenOverlay/files/5371590/DxDiag.txt)

**Comment by y33y** [comment] 2020-10-14 07:57
exactly same here.  Tried extracting in multiple directories, running as administrator, and disabling antivirus. but it doesn't work.

**Comment by whiskeyjack3** [comment] 2020-10-14 08:25
Same issue, Here is my DxDiag for your help. 

[DxDiag.txt](https://github.com/TekkenOverlay/TekkenOverlay/files/5376716/DxDiag.txt)

**Comment by y33y** [comment] 2020-10-14 08:33
[DxDiag.txt](https://github.com/TekkenOverlay/TekkenOverlay/files/5376773/DxDiag.txt)
Here is my DxDiag for your help.

**Comment by KulaGGin** [comment] 2020-10-17 18:42
Another reason you can get this error is because of VC++ Redistributables installed. Install VC++ Redistributables 2015-2019 from [here](https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads). This should fix the `Injecting DLL... FAIL!` error.

Let us know if installing the 2015-2019 of VC++ fixes the error for you.

**Comment by TragicFour** [comment] 2020-10-17 19:45
> Let us know if installing the 2015-2019 of VC++ fixes the error for you.

FIXED for me .... Thank you 8)

**Comment by y33y** [comment] 2020-10-18 07:44
> Another reason you can get this error is because of VC++ Redistributables installed. Install VC++ Redistributables 2015-2019 from [here](https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads). This should fix the `Injecting DLL... FAIL!` error.
> 
> Let us know if installing the 2015-2019 of VC++ fixes the error for you.

Thank you so much!! FIXED!!

**Comment by massivemax** [comment] 2020-10-24 14:03
I'm still getting the error, neither of the solutions work for me. Interestingly enough, I get "Injecting DLL... SUCCESS!" message, but only when the game is closing.

**Comment by WAZAAAAA0** [comment] 2020-11-02 04:21
Found a way to fix `Injecting DLL... FAIL!` on both Win7 and Win10 that worked for me: I just removed a XINPUT1_4.dll reference by modding tekken-overlay.dll.

For those who want to apply the fix themselves these are the steps to follow using CFF Explorer:
`right click tekken-overlay.dll > Open with CFF Explorer > Import Directory > right click XINPUT1_4.dll > Delete Import Descriptor > File > Save`
or just download this version with the fix applied: [TekkenOverlay-3.33.1-2020-11-02.zip](https://github.com/TekkenOverlay/TekkenOverlay/files/5472791/TekkenOverlay-3.33.1-2020-11-02.zip)

**Comment by wlsvyh** [comment] 2020-11-15 01:44
Version 3.33 works fine, but version 4.00.1 does not. I installed 2015-2019 of VC++ but it still doesn't work. Ask for help.

**Comment by ParkourGrip** [comment] 2020-11-15 02:20
If nothing else works for you you might want to try to install `Visual Studio 2019 Community`. It's not a small program but it you desperately want to use this mod by any cost you can install it.

**Comment by hhm-h** [comment] 2020-11-15 19:43
4.00.0 injecting dll fail..
help Other reasons you can get this error is because of VC+++ Redistributes installed. Install VC++ Redistributes 2015-2019 from here. This should fix the Injecting DLL... FAIL! error.

Let us know if installing the 2015-2019 of VC+++ fixes the error for you. I've tried this, but it hasn't been fixed. Help me.

**Comment by wlsvyh** [comment] 2020-11-16 00:57
> If nothing else works for you you might want to try to install `Visual Studio 2019 Community`. It's not a small program but if you desperately want to use this mod by any cost you can install it.

How can I use Visual Studio 2019 Community to solve the problem? Just install it?

**Comment by KulaGGin** [comment] 2020-11-18 14:11
Apparently, it was imgui that was linking XInput. Disabled linking XInput in imgui and now it doesn't add that XInput to import directory of the tekken-overlay.dll.

It should fix the issue for people who get XInput1_4.dll errors.

Kudos to WAZAAAAA.

You can try if this version with removed XInput works for you.

[TekkenOverlay-4.00.1-[2020-11-18].zip](https://github.com/TekkenOverlay/TekkenOverlay/files/5560527/TekkenOverlay-4.00.1-.2020-11-18.zip)

**Comment by wlsvyh** [comment] 2020-11-18 15:27
I guess I have a different problem with this one. In ver 3.33, I solved it by reinstalling Windows (before Reason #2 was confirmed).

But this time, even if you use the same method as last time, and install VC++ Redistributables 2015-2019, it does not work.

I look forward to seeing a solution someday.

> Apparently, it was imgui that was linking XInput. Disabled linking XInput in imgui and now it doesn't add that XInput to import directory of the tekken-overlay.dll.
> 
> It should fix the issue for people who get XInput1_4.dll errors.
> 
> Kudos to WAZAAAAA.
> 
> You can try if this version with removed XInput works for you.
> 
> [TekkenOverlay-4.00.1-[2020-11-18].zip](https://github.com/TekkenOverlay/TekkenOverlay/files/5560527/TekkenOverlay-4.00.1-.2020-11-18.zip)

I guess I have a different problem with this one. In ver 3.33, I solved it by reinstalling Windows (before Reason #2 was confirmed).

But this time, even if you use the same method as last time, and install VC++ Redistributables 2015-2019, it does not work.

I look forward to seeing a solution someday.

**Comment by wlsvyh** [comment] 2020-11-22 18:08
> > Apparently, it was imgui that was linking XInput. Disabled linking XInput in imgui and now it doesn't add that XInput to import directory of the tekken-overlay.dll.
> > It should fix the issue for people who get XInput1_4.dll errors.
> > Kudos to WAZAAAAA.
> > You can try if this version with removed XInput works for you.
> > [TekkenOverlay-4.00.1-[2020-11-18].zip](https://github.com/TekkenOverlay/TekkenOverlay/files/5560527/TekkenOverlay-4.00.1-.2020-11-18.zip)
> 
> I guess I have a different problem with this one. In ver 3.33, I solved it by reinstalling Windows (before Reason #2 was confirmed).
> 
> But this time, even if you use the same method as last time, and install VC++ Redistributables 2015-2019, it does not work.
> 
> I look forward to seeing a solution someday.

The Korean alphabet in the folder path was the problem.
When I moved it to a folder that does not contain Korean, it works fine. (Ver 4.00 only. Ver 3.33 is no problem anywhere)
Thank you for the project.

**Closed** 2023-05-01 21:11 UTC
Labels: bug
