### ISSUE TITLE
Not an issue but a request

### ISSUE THREAD

**Issue by CeroYuriy** [TekkenOverlay/TekkenOverlay#88] opened 2022-08-24 15:06 UTC
I couldn't find anywhere else to request this but could you please make the overlay show if the moves are high, mid or low?

**Comment by ParkourGrip** [comment] 2022-08-24 22:29
Duplicate of: https://github.com/TekkenOverlay/TekkenOverlay/issues/35

**Closed by ParkourGrip** 2022-08-24 22:29 UTC
