### ISSUE TITLE
The (overlay) in your name

### ISSUE THREAD

**Issue by justatempnamefornow** [TekkenOverlay/TekkenOverlay#41] opened 2021-03-29 20:20 UTC
the overlay in the name is just a great reason for people to be super toxic/mad. Is there a reason this was added? And is it possible to disable it?

**Comment by lmaok549** [comment] 2021-03-29 20:24
This is what ParkourGrip told me hours ago.

> Working as intended. No need to hide if you are using it. No sneaky online tournament hackers allowed.

We tagged now if we use this

**Comment by ParkourGrip** [comment] 2021-03-29 20:28
Duplicate of: #40

**Closed by ParkourGrip** 2021-03-29 20:28 UTC
